name: qrcp

version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  mime: ^2.0.0
  qr: ^3.0.1
  shelf: ^1.4.1
  shelf_router: ^1.0.0

dev_dependencies:
  custom_lints:
    git: https://github.com/SkinnyMind/custom_lints
